const {chromium}=require('playwright-core');
const {spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const records=path.resolve('.scratch/memory-stage-4');
const checkpoint=JSON.parse(fs.readFileSync(path.join(records,'148-checkpoint.json')));
const report={tree:checkpoint.tree,synthetic:true,owner_pilot:false,browser:'isolated headless Chrome',steps:[],responses:[],page_errors:[]};
let server,serverDone,browser,page,fixtureDB,metadata;
(async()=>{
 server=spawn(path.join(checkpoint.snapshot,'.scratch/memory-stage-4/148-browser-fixture/demo'),[],{stdio:['ignore','pipe','pipe']});
 serverDone=new Promise(resolve=>server.once('exit',(code,signal)=>resolve({code,signal})));
 const url=await new Promise((resolve,reject)=>{let output='';server.stdout.on('data',chunk=>{output+=chunk;const m=output.match(/BROWSER_DIAGNOSTIC=(.+)/);if(m)metadata=JSON.parse(m[1]);const db=output.match(/BROWSER_FIXTURE_DB=(.+)/);if(db)fixtureDB=db[1];const u=output.match(/BROWSER_FIXTURE_URL=(.+)/);if(u)resolve(u[1]);});server.stderr.on('data',chunk=>report.server_stderr=(report.server_stderr||'')+chunk);server.once('exit',code=>reject(new Error('Fixture exited '+code+' '+report.server_stderr)));});
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});report.browser_version=browser.version();
 page=await (await browser.newContext({viewport:{width:1440,height:1100}})).newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>report.page_errors.push(e.message));
 page.on('response',r=>{if(r.url().includes('/api/memory/'))report.responses.push({route:r.url().split('/memory/')[1],status:r.status()});});
 const button=name=>page.getByRole('button',{name,exact:true});
 const health=()=>page.getByRole('region',{name:'Compiler health',exact:true});
 const request=async(action,route='diagnostics')=>{const pending=page.waitForResponse(r=>r.url().endsWith('/api/memory/compiler/'+route)&&r.request().method()==='POST');const [response]=await Promise.all([pending,action()]);const body=await response.json();assert.equal(response.status(),200,JSON.stringify(body));await page.waitForFunction(()=>!Array.from(document.querySelectorAll('[role=status]')).some(e=>e.textContent.includes('Loading bounded diagnostics')));return body;};
 const view=async name=>request(()=>page.getByLabel(/^Diagnostic view/).selectOption(name));
 const text=()=>health().innerText();
 await page.goto(url);await button('Memory').click();assert.equal(await health().count(),0);await button('Compiler health').click();
 await request(()=>page.getByLabel(/^Memory scope/).selectOption('global'),'sessions');
 let jobs=await request(()=>page.getByLabel(/^Session/).selectOption(metadata.session_id));
 const find=id=>jobs.jobs.find(j=>j.job_id===id);
 assert.equal(find(metadata.earlier_job).state,'failed');assert.equal(find(metadata.earlier_job).completed_new_events,0);
 assert.equal(find(metadata.later_job).state,'completed_candidates');assert.equal(find(metadata.later_job).completed_new_events,find(metadata.later_job).selected_new_events);
 assert.equal(find(metadata.unavailable_job).reason,'endpoint_unavailable');assert.equal(find(metadata.unavailable_job).state,'retry_wait');assert.equal(jobs.capacity_state,'available');
 assert.equal(find(metadata.later_job).candidate_freshness_nanos,null);assert(find(metadata.later_job).publication_nanos!==null);
 assert((await text()).includes('Unavailable / incomplete'));assert((await text()).includes('endpoint_unavailable'));
 await health().getByText('Selected and completed counts refer to new evidence.',{exact:false}).scrollIntoViewIfNeeded();await page.screenshot({path:path.join(records,'148-browser-jobs.png')});
 report.steps.push({name:'Closed-session failed gap, later success, actual unavailable endpoint, measured publication and explicitly missing freshness',pass:true});
 const selections=await view('selections');assert.equal(selections.view,'selections');
 const roots=await view('live_roots');assert(roots.live_roots.some(r=>r.state==='deferred_live'));
 const activations=await view('activations');assert.equal(activations.activations.length,1);
 const history=await view('history');assert.equal(history.history.length,1);assert((await text()).includes('scanned cursor records discovery'));
 report.steps.push({name:'Selected units, unfinished live obligation, explicit activation frontier and historical selection remain distinct',pass:true});
 await page.getByLabel(/^Diagnostic view/).selectOption('selection');await page.getByLabel(/^Exact generation ID/).fill(metadata.earlier_generation);
 const selection=await request(()=>button('Refresh diagnostics').click());assert(selection.selection.some(r=>r.membership==='selected_history'));assert(selection.selection.some(r=>r.membership==='outside_selection'));assert(selection.next_cursor);
 const next=await request(()=>button('Next diagnostic page').click());assert(next.selection.some(r=>r.membership==='selected_live'));assert(!next.selection.some(r=>r.event_id===selection.selection[0].event_id));
 const refreshed=await request(()=>button('Refresh diagnostics').click());assert.equal(refreshed.selection[0].event_id,selection.selection[0].event_id);
 await page.getByLabel(/^Exact generation ID/).fill(metadata.later_generation);assert.equal(await health().getByRole('table').count(),0);
 const changed=await request(()=>button('Refresh diagnostics').click());assert(changed.selection.every(r=>r.membership==='outside_selection'));
 report.steps.push({name:'Generation-specific event membership, bounded next-page replacement and refresh from first page',pass:true});
 let candidates=await view('candidates');for(let n=0;!candidates.candidates.length&&candidates.next_cursor&&n<3;n++)candidates=await request(()=>button('Next diagnostic page').click());assert(candidates.candidates.some(c=>c.review_state==='unresolved'));assert((await text()).includes('Active measured review time must be collected during the pilot'));
 assert.equal(await health().getByRole('button',{name:/Accept|Reject|Edit interpretation/}).count(),0);
 const foreground=await view('foreground');assert.deepEqual(foreground.foreground,[]);assert((await text()).includes('Missing observations'));
 report.steps.push({name:'Metadata-only review backlog and honest missing foreground observations; no inferred human review duration',pass:true});
 // Hold a real HTTP response, navigate to another view, then release it. The
 // delayed page must not restore data from the previous navigation epoch.
 let release,seen,delivered;const deliveryPromise=new Promise(resolve=>delivered=resolve);const seenPromise=new Promise(resolve=>seen=resolve);const held=new Promise(resolve=>release=resolve);
 const pattern='**/api/memory/compiler/diagnostics';
 await page.route(pattern,async route=>{const body=route.request().postDataJSON();if(body.input.view==='jobs'){const response=await route.fetch();seen();await held;await route.fulfill({response});delivered();}else await route.continue();});
 await page.getByLabel(/^Diagnostic view/).selectOption('jobs');await seenPromise;
 await view('foreground');release();await deliveryPromise;await page.unroute(pattern);await page.waitForLoadState('networkidle');
 assert.equal(await page.getByLabel(/^Diagnostic view/).inputValue(),'foreground');assert(!(await text()).includes(metadata.earlier_job));
 report.steps.push({name:'Late real HTTP response cannot restore the old diagnostic view',pass:true});
 await page.getByLabel(/^Memory scope/).selectOption('');assert.equal(await health().getByText(metadata.session_id,{exact:true}).count(),0);assert((await text()).includes('Choose a memory scope to begin.'));
 await page.screenshot({path:path.join(records,'148-browser-final.png')});assert.deepEqual(report.page_errors,[]);report.pass=true;report.completed_at=new Date().toISOString();
})().catch(async error=>{report.pass=false;report.error=error.stack;if(page){fs.writeFileSync(path.join(records,'148-browser-failure-dom.txt'),await page.locator('body').innerText().catch(()=>''));await page.screenshot({path:path.join(records,'148-browser-failure.png')}).catch(()=>{});}process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server){server.kill('SIGINT');report.server_exit=await serverDone;}report.fixture_directory_removed=fixtureDB?!fs.existsSync(path.dirname(fixtureDB)):null;report.driver_sha256=crypto.createHash('sha256').update(fs.readFileSync(__filename)).digest('hex');fs.writeFileSync(path.join(records,'148-browser-verification.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));});
