import type { CompilerDiagnostics, CompilerDiagnosticsAPI } from "../api/compilerDiagnostics";
import type { DiagnosticsState } from "./controller";
export const diagnosticPage: CompilerDiagnostics = {
 scope_key: "global", session_id: "closed-session", view: "jobs", as_of_unix_ms: 200000, revision: 7, indexing: false, counts: { jobs_failed: 1, jobs_completed_candidates: 1, candidates_unresolved: 1 }, capacity_state: "available", next_cursor: "next-page",
 jobs: [{ job_id: "earlier-gap", generation_id: "generation-1", session_id: "closed-session", first_sequence: 1, last_sequence: 3, state: "failed", reason: "attempts_exhausted", attempts: 5, lane: "new", recovery: "select a new generation", queued_at_unix_ms: 1000, published_at_unix_ms: null, selected_new_events: 2, completed_new_events: 0, candidate_freshness_nanos: null, publication_nanos: null, measurements: [{ attempt: 5, fence: 7, claimed_at_unix_ms: 2000, queue_wait_nanos: 1000, inference_nanos: null, validation_nanos: null, database_completion_nanos: null, observed_outcome: "incomplete" }] }, { job_id: "later-success", generation_id: "generation-2", session_id: "closed-session", first_sequence: 4, last_sequence: 7, state: "completed_candidates", attempts: 1, lane: "new", queued_at_unix_ms: 2000, published_at_unix_ms: 3000, selected_new_events: 1, completed_new_events: 1, candidate_freshness_nanos: null, publication_nanos: null, measurements: [] }],
 candidates: [], activations: [], history: [], selection: [], foreground: [], selections: [], live_roots: [],
};
export function diagnosticAPI(overrides: Partial<CompilerDiagnosticsAPI> = {}): CompilerDiagnosticsAPI {
 return { scopes: async () => ({ scopes: [{ scope_key: "global", kind: "global", label: "Global memory" }], next_cursor: "", indexing: false }), sessions: async () => ({ session_ids: ["closed-session"] }), inspect: async (_scope, query) => ({ ...diagnosticPage, view: query.view }), ...overrides };
}
export const diagnosticState: DiagnosticsState = { scope: "global", session: "closed-session", view: "jobs", generation: "", generations: ["generation-1", "generation-2"], scopesBusy: false, busy: false, problem: "", scopes: { scopes: [{ scope_key: "global", kind: "global", label: "Global memory" }], next_cursor: "more-scopes", indexing: false }, sessions: { session_ids: ["closed-session"], next_cursor: "more-sessions" }, page: diagnosticPage };
