import type { CandidateSource, ReviewClaimEffect, ReviewSource, ReviewPreview, ReviewEffect, CandidateProposal, EditRevision } from "../api/candidateReview";
import { supportedPreview } from "./previewSupport";
export function CandidateSources({ title, sources }: { title: string; sources: CandidateSource[] }) {
  if (!sources.length) return null;
  return <section className="mt-4"><h4 className="text-muted-text text-xs font-medium">{title}</h4>{sources.map((source, index) => <Evidence key={`${source.locator.event_id}:${index}`} evidence={source.evidence} authority={source.authority} session={source.session_id} scope={source.scope_key} observedAt={source.observed_at} locator={source.locator} observation={source.observation} actor={source.actor} sourceType={source.source_type} />)}</section>;
}

function Evidence({ evidence, authority, session, scope, observedAt, locator, observation, actor, sourceType }: { evidence: string; authority: string; session: string; scope: string; observedAt: string; locator: CandidateSource["locator"]; observation?: CandidateSource["observation"]; actor?: string; sourceType?: string }) {
  return <div className="border-hair mt-2 border-l-2 pl-3"><blockquote className="whitespace-pre-wrap break-words py-1">{evidence || "Evidence unavailable under current source policy."}</blockquote><p className="text-muted-text text-xs">Authority: {authority} · observed {observedAt}</p><details className="text-muted-text mt-1 break-all text-xs"><summary>Exact source</summary><p>Conversation: {session}</p><p>Scope: {scope}</p><p>Event: {locator.event_id} · {locator.event_part} · {locator.locator_kind} {locator.locator_value}</p><p>Evidence hash: {locator.evidence_sha256}</p><p>Original actor: {actor ?? "See source authority"} · event type: {sourceType ?? "See exact source"}</p>{observation && <p>Observation contract: {observation.contract} · root {observation.root_id} · execution {observation.execution_id} · call {observation.call_id} · ancestry {observation.ancestry_sha256}. Local display has no inferred timezone.</p>}</details></div>;
}

function SupportingSource({ source }: { source: ReviewSource }) { return <Evidence evidence={source.evidence} authority={source.authority} session={source.session_id} scope={source.source_scope_key} observedAt={source.observed_at} locator={source} actor={source.actor} sourceType={source.source_type} />; }

export function ClaimEffect({ effect }: { effect: ReviewClaimEffect }) {
  const claim = effect.claim;
  return <section className="border-hair mt-4 border-t pt-3">
    <p className="text-ink font-medium">{effect.subject.canonical_name} · {effect.predicate.label} · {effect.object_entity?.canonical_name ?? claim.object.literal?.value}</p>
    <dl className="mt-2 grid grid-cols-[auto_1fr] gap-x-4 gap-y-1 text-xs"><dt>Subject identity</dt><dd>{effect.subject.create ? "Create distinct Entity" : "Reuse Entity"} · {effect.subject.entity_id}</dd>{effect.object_entity && <><dt>Object identity</dt><dd>{effect.object_entity.create ? "Create distinct Entity" : "Reuse Entity"} · {effect.object_entity.entity_id}</dd></>}<dt>Predicate definition</dt><dd>{effect.predicate.create ? "Create global Predicate definition" : "Reuse Predicate definition"}</dd><dt>Change</dt><dd>{effect.create ? "Create claim" : "Reuse existing claim"}</dd><dt>Polarity</dt><dd>{claim.polarity}</dd><dt>Scope</dt><dd className="break-all">{claim.scope_key}</dd><dt>Value type</dt><dd>{claim.object.literal?.kind ?? "Entity"}</dd><dt>Valid from</dt><dd>{claim.valid_time.from ?? "Unknown"}</dd><dt>Valid until</dt><dd>{claim.valid_time.to ?? "Unknown"}</dd><dt>Predicate</dt><dd>{effect.predicate.token} · version {effect.predicate.version} · {effect.predicate.object_constraint} · {effect.predicate.cardinality}</dd></dl>
    {effect.temporal_qualification && <p className="mt-2 text-xs">Time qualification: {effect.temporal_qualification}</p>}
    {effect.conflicts.map((conflict, i) => <p key={i} className="text-amber-ink mt-2 break-all text-xs">Conflict: {conflict.code} · claims {conflict.claim_ids.join(", ")}. This review does not choose a winner.</p>)}
    <h4 className="text-muted-text mt-4 text-xs">Supporting Source Links</h4>{effect.sources.map((source) => <div key={source.source_link_id}><p className="text-muted-text mt-2 text-xs">{source.create ? "Add source" : "Reuse source"}</p><SupportingSource source={source} /></div>)}
    <CandidateSources title="Interpretation context (authority none)" sources={effect.context} />
    <details className="text-muted-text mt-3 break-all text-xs"><summary>Exact effect identities</summary><p>Claim: {claim.claim_id}</p><p>Subject: {effect.subject.entity_id}</p><p>Predicate: {effect.predicate.predicate_id}</p>{effect.object_entity && <p>Object: {effect.object_entity.entity_id}</p>}{effect.sources.map((source) => <p key={source.source_link_id}>Source Link: {source.source_link_id}</p>)}</details>
  </section>;
}


export function ProposalMeaning({ proposal }: { proposal: CandidateProposal }) {
 return <dl className="mt-2 grid grid-cols-[auto_1fr] gap-x-4 gap-y-1 text-xs"><dt>Meaning</dt><dd>{proposal.temporal?.meaning ?? "assertion"}</dd><dt>Subject</dt><dd>{proposal.identity?.subject?.name ?? proposal.proposition.subject_entity_id}</dd><dt>Relationship</dt><dd>{proposal.identity?.predicate?.label ?? proposal.proposition.predicate_id}</dd><dt>Object</dt><dd>{proposal.identity?.object?.name ?? proposal.proposition.object.literal?.value ?? proposal.proposition.object.entity_id}</dd><dt>Value kind</dt><dd>{proposal.proposition.object.literal?.kind ?? "Entity"}</dd><dt>Polarity</dt><dd>{proposal.proposition.polarity}</dd><dt>Valid from / until</dt><dd>{proposal.valid_time.from ?? "Unknown"} / {proposal.valid_time.to ?? "Unknown"}</dd><dt>Time qualification</dt><dd>{proposal.temporal_qualification || "None supplied"}</dd>{proposal.identity && <><dt>Identity uncertainty</dt><dd>{proposal.identity.uncertainty || "None supplied"}</dd><dt>Extractor confidence (not authority)</dt><dd>{proposal.identity.confidence ?? "Unknown"}</dd></>}{proposal.temporal?.correction && <><dt>Proposed correction modes</dt><dd>{proposal.temporal.correction.modes.join(", ")}</dd><dt>Proposed effective time</dt><dd>{proposal.temporal.correction.effective_time ?? "Unknown"}</dd></>}</dl>;
}
export function EditLineage({ edit }: { edit: EditRevision }) {
 return <section aria-label="Owner edit lineage" className="border-hair mt-4 border-t pt-3"><h4>Owner interpretation {edit.revision}, from revision {edit.parent_revision}</h4><p className="text-muted-text text-xs">Audit {edit.audit_id}. This edit and its reason are owner interpretation, not new factual evidence.</p><p>Reason: {edit.reason || "None supplied"}</p><div className="grid gap-4 md:grid-cols-2"><section><h5>Before edit</h5><ProposalMeaning proposal={edit.before.proposal}/><CandidateSources title="Prior supporting evidence" sources={edit.before.support}/><CandidateSources title="Prior context" sources={edit.before.context}/></section><section><h5>After edit</h5><ProposalMeaning proposal={edit.after.proposal}/><CandidateSources title="Edited supporting evidence" sources={edit.after.support}/><CandidateSources title="Edited context" sources={edit.after.context}/></section></div><CanonicalDisclosure value={edit} title="Complete edit revision, including prior identity and correction choices"/></section>;
}
export function CanonicalDisclosure({ value, title = "Complete canonical disclosure" }: { value: unknown; title?: string }) { return <details className="text-muted-text mt-3 text-xs"><summary>{title}</summary><pre className="whitespace-pre-wrap break-all p-2">{JSON.stringify(value, null, 2)}</pre></details>; }
export function ReviewEffects({ preview }: { preview: ReviewPreview }) {
 if (!supportedPreview(preview, !!preview.batch_preview_id)) return <p className="text-amber-ink mt-3">Additional review is required to display all effects of this operation.</p>;
 return <>{preview.candidates.map((item) => <section key={item.ref.candidate_id} className="mt-4"><p className="text-muted-text text-xs">Candidate {item.ref.candidate_id} · generation {item.generation_id} · interpretation {item.ref.interpretation_revision}</p>{!item.redacted && <><ProposalMeaning proposal={item.candidate.proposal}/><CandidateSources title="Original supporting authority and observation contracts" sources={item.candidate.support ?? []}/>{item.original && <details><summary>Original extraction and unchanged source window</summary><ProposalMeaning proposal={item.original.proposal}/><CandidateSources title="Original supporting evidence" sources={item.original.support ?? []}/><CandidateSources title="Original interpretation context" sources={item.original.context ?? []}/></details>}{item.edit && <EditLineage edit={item.edit}/>}</>}</section>)}{preview.effect && <EffectDisclosure effect={preview.effect}/>}<CanonicalDisclosure value={preview}/></>;
}
function EffectDisclosure({ effect }: { effect: ReviewEffect }) {
 if (effect.version === "owner-review-effect-v5") return <><h4 className="mt-4 font-medium">Atomic group: all member changes succeed together</h4><DependencyDisclosure dependencies={effect.dependencies ?? []}/>{effect.members?.map((member, i) => <section key={i}><h5 className="mt-4">Member {i + 1}</h5><EffectDisclosure effect={member}/></section>)}<h4 className="mt-4">Complete semantic record changes</h4><table className="mt-2 w-full text-left text-xs"><thead><tr><th>Kind and ID</th><th>Action</th><th>Lifecycle</th></tr></thead><tbody>{effect.records?.map((record,i) => <tr key={i}><td className="break-all">{record.kind}: {record.id}</td><td>{record.action}</td><td>{record.before_state || "—"} → {record.after_state || "—"}</td></tr>)}</tbody></table></>;
 return <>{effect.identity && <section className="mt-4"><h4>Explicit identity decisions</h4><p className="text-xs">Interpretation {effect.identity.revision.revision}; alternatives remain retained. Reusing a name never merges distinct Entities.</p>{effect.identity.aliases.map((alias) => <p className="mt-2 text-xs" key={alias.alias_id}>{alias.create ? "Create Alias" : "Reuse Alias"}: {alias.value} → Entity {alias.entity_id}; Alias {alias.alias_id}; scope {alias.scope_key}; source {alias.source_event_id}</p>)}<CanonicalDisclosure value={effect.identity.revision} title="Chosen identities and all reviewed alternatives"/></section>}{effect.correction && <section aria-label="Correction effects" className="text-amber-ink mt-4"><h4>Correction: {effect.correction.mode === "error" ? "Earlier statement was an error" : "Real-world state changed"}</h4><p>Old claim {effect.correction.old_claim.claim_id}: {effect.correction.old_claim.polarity} {effect.correction.old_claim.object.literal?.value ?? effect.correction.old_claim.object.entity_id}</p><p>Lifecycle: {effect.correction.old_state.state} → {effect.correction.transition.state}</p><p>Effective time: {effect.correction.effective_time ?? "Unknown"}</p><p>Old validity before: {effect.correction.valid_time_effect.old_before.from ?? "Unknown"} / {effect.correction.valid_time_effect.old_before.to ?? "Unknown"}</p><p>Old validity after: {effect.correction.valid_time_effect.old_after.from ?? "Unknown"} / {effect.correction.valid_time_effect.old_after.to ?? "Unknown"}</p><p>Replacement validity: {effect.correction.valid_time_effect.replacement.from ?? "Unknown"} / {effect.correction.valid_time_effect.replacement.to ?? "Unknown"}</p></section>}{effect.claims.map((claim) => <ClaimEffect key={claim.claim.claim_id} effect={claim}/>)}</>;
}
export function DependencyDisclosure({ dependencies }: { dependencies: import("../api/candidateReview").ReviewDependency[] }) { return <section className="mt-3"><h4>Explicit dependency closure</h4>{dependencies.length ? <ul>{dependencies.map((dep,i) => <li className="mt-1 break-all text-xs" key={i}>{dep.candidate_id} {dep.field} uses the exact {dep.from_field} created by {dep.from_candidate_id}.</li>)}</ul> : <p className="text-xs">No proposed identities are shared by dependency binding in this group.</p>}</section>; }
