import type { BatchPreview, BatchResult, IdentityOptions, OwnerCandidate, ReviewEffect, ReviewPreview, TemporalOptions } from "../api/candidateReview";
import { candidate, preview, result } from "./fixtures.test-support";

export const identityCandidate: OwnerCandidate = { ...structuredClone(candidate), candidate: { ...structuredClone(candidate.candidate), proposal: { ...structuredClone(candidate.candidate.proposal), identity: { subject: { name: "Maya", entity_type: "person", support: candidate.candidate.support![0].locator }, object: null, predicate: { token: "enjoys", label: "Enjoys", object_constraint: "text", cardinality: "many" }, uncertainty: "Two people share this name", confidence: 0.4 } } } };
export const identityOptions: IdentityOptions = { candidate: candidate.ref, scope_key: "global", options_sha256: "identity-options-hash", scope_revisions: [{ scope_key: "global", revision: 1 }], subject: [1,2].map((n) => ({ entity: { entity_id: `maya-${n}`, canonical_name: "Maya", entity_type: "person", scope_key: "global" }, aliases: [{ alias_id: `alias-${n}`, entity_id: `maya-${n}`, scope_key: "global", value: `Maya ${n}`, normalized_value: `maya ${n}`, source_event_id: `event-${n}`, create: false }], context: [{ ...preview.effect!.claims[0].claim, claim_id: `context-${n}`, object: { literal: { kind: "text", value: n === 1 ? "Designer" : "Physician" } } }] })), object: [], predicates: [] };
export const chosenCandidate: OwnerCandidate = { ...identityCandidate, ref: { ...candidate.ref, interpretation_revision: 1, review_revision: 1 }, identity: { revision: 1, parent_revision: 0, review_revision: 1, audit_id: "identity-audit", options: identityOptions, choices: { subject: { entity_id: "", create: true }, object: null, predicate: { predicate_id: "", create: true } } } };
export const identityEffect: ReviewEffect = { ...structuredClone(preview.effect!), version: "owner-review-effect-v2", claims: [{ ...structuredClone(preview.effect!.claims[0]), candidate: chosenCandidate.ref, subject: { entity_id: "new-maya", canonical_name: "Maya", entity_type: "person", scope_key: "global", create: true }, predicate: { predicate_id: "new-enjoys", label: "Enjoys", token: "enjoys", object_constraint: "text", cardinality: "many", version: 1, create: true } }], identity: { revision: chosenCandidate.identity!, aliases: [{ alias_id: "alias-maya", entity_id: "new-maya", scope_key: "global", value: "Maya", normalized_value: "maya", source_event_id: "event-1", create: true }] } };
export const identityPreview: ReviewPreview = { ...preview, version: "owner-review-preview-v2", candidates: [chosenCandidate], effect: identityEffect };
export const temporalOptions: TemporalOptions = { candidate: candidate.ref, scope_key: "global", scope_revisions: [{ scope_key: "global", revision: 1 }], options_sha256: "temporal-options-hash", modes: ["error", "changed"], effective_time: null, alternatives: [{ claim: { ...preview.effect!.claims[0].claim, claim_id: "old-tea", object: { literal: { kind: "text", value: "tea" } } }, state: { state: "active", operation_id: "old-op", scope_revision: 1, transaction_time: "2026-01-01T00:00:00Z" } }] };
export const correctionPreview: ReviewPreview = { ...preview, version: "owner-review-preview-v3", effect: { ...structuredClone(preview.effect!), version: "owner-review-effect-v3", correction: { revision: { revision: 1, parent_revision: 0, review_revision: 1, audit_id: "temporal-audit", options: temporalOptions, choice: { old_claim_id: "old-tea", mode: "error" } }, old_claim: temporalOptions.alternatives[0].claim, old_state: temporalOptions.alternatives[0].state, mode: "error", effective_time: null, valid_time_effect: { old_before: { from: null, to: null }, old_after: { from: null, to: null }, replacement: { from: null, to: null } }, transition: { object_kind: "claim", object_id: "old-tea", state: "superseded" } } } };
const second = { ...structuredClone(candidate), ref: { ...candidate.ref, candidate_id: "candidate-2" } };
export const batchRequest = { groups: [{ group_id: "together", action: "accept" as const, candidates: [chosenCandidate.ref, second.ref], dependencies: [{ candidate_id: "candidate-2", field: "subject", from_candidate_id: "candidate-1", from_field: "subject" }] }, { group_id: "independent", action: "reject" as const, candidates: [{ ...candidate.ref, candidate_id: "candidate-3" }], dependencies: [] }] };
const member2 = { ...structuredClone(identityEffect), claims: [{ ...structuredClone(identityEffect.claims[0]), candidate: second.ref, claim: { ...identityEffect.claims[0].claim, claim_id: "claim-3" } }] };
export const batchPreview: BatchPreview = { version: "owner-review-batch-v1", preview_id: "batch-1", preview_sha256: "batch-hash", scope_key: "global", source_policy: "policy", prior_revisions: [{ scope_key: "global", revision: 1 }], failure_behavior: "atomic_groups_independent_failures; committed_failures_are_not_retried", groups: [{ group_id: "together", preview: { ...identityPreview, version: "owner-review-preview-v5", preview_id: "group-1", batch_preview_id: "batch-1", candidates: [chosenCandidate,second], dependencies: batchRequest.groups[0].dependencies, effect: { version: "owner-review-effect-v5", operation_id: "operation-1", prior_revisions: [{ scope_key: "global", revision: 1 }], claims: [...identityEffect.claims,...member2.claims], members: [identityEffect,member2], dependencies: batchRequest.groups[0].dependencies, records: [{ kind: "entity", id: "new-maya", action: "create", before_state: "", after_state: "" }, { kind: "state_event", id: "old-tea", action: "transition", before_state: "active", after_state: "superseded" }] } } }, { group_id: "independent", preview: { ...preview, version: "owner-review-preview-v5", preview_id: "group-2", batch_preview_id: "batch-1", action: "reject", candidates: [{ ...candidate, ref: batchRequest.groups[1].candidates[0] }], effect: null } }] };
export const batchResult: BatchResult = { delivery_key: "idem:v1:batch-delivery", preview_id: "batch-1", groups: [{ group_id: "together", outcome: "accepted", failure_code: "", result }, { group_id: "independent", outcome: "failed", failure_code: "source_ineligible", result: null }] };
