from pathlib import Path
import datetime,hashlib,json,re
base=Path('cmd/evie/docs/fixtures/memory-stage-4-spike/v1');new=base/'qwen-compact-v3';reports=new/'reports'
def sha(p):return 'sha256:'+hashlib.sha256(p.read_bytes()).hexdigest()
def canon(v):return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False)
def save(p,v):
 with p.open('x') as f:json.dump(v,f,indent=2,ensure_ascii=False);f.write('\n')
r=json.loads((reports/'development.json').read_text());score=json.loads((reports/'development-initial-score.json').read_text());bycase={x['case_id']:x for x in r['runs']};gold={x['case_id']:x for x in json.loads((base/'development.gold.json').read_text())['cases']}
labels=[
('unsupported',['source_attribution'],'Repeats the older tea preference from overlap alone. The newly owned pear meal supplies no support for this preference. Unsupported here means an ineligible repeated truth, not a fabricated historical preference.'),
('unsupported',['identity','source_attribution'],'Retained, but treats a fictional first-person line and an unendorsed Maya report as the owner living in Paris. Exact source copying does not supply the missing owner assertion.'),
('unsupported',['identity','typed_meaning','source_attribution'],'Retained, but the owner never asserts a decision or enduring consideration to move to Paris. The source concerns a story and Maya\'s unendorsed report; changing it into the owner\'s choice is unsupported.'),
('unsupported',['identity','source_attribution'],'Retained, but the new endorsement concerns Maya the neighbor, not the owner. The subject is explicitly owner; no new-Entity identity is proposed.'),
('unsupported',['typed_meaning'],'Retained with correct assistant question context, but preference=tea and kind=decision lose the reviewed standing tea-over-coffee comparison/fact encoding. This raw object is byte-for-byte identical after canonical JSON encoding to pending compact-v2 V07; no second independent judgment or automatic approval is inferred.'),
('unsupported',['identity','source_attribution'],'Retained, but She is ambiguous between Maya Chen and Maya Patel. The output instead assigns Paris residence to the owner, which the source does not assert.'),
('unsupported',['source_attribution'],'The offline requirement is an older true project constraint, supported only by overlap. The new PostgreSQL consideration does not own this separate constraint; no new candidate is eligible.'),
('optional_useful',['identity','predicate'],'Proposed optional raw credit recognizes the explicitly unadopted PostgreSQL consideration. The exact predicate=decision conflicts with kind=consideration, and project/text is incorrectly unresolved. Human judgment is needed for raw credit; approval would not repair identity, create retention or supply required recall.'),
('unsupported',['predicate','source_attribution'],'Repeats the old SQLite decision from overlap as a preference. No newly owned source supports this separate old decision; the newly owned PostgreSQL option does not change that ownership.'),
('unsupported',['polarity','typed_meaning'],'Retained, but emits affirmative employment/work at Acme as fact with last month, instead of the explicit departure/denied world-change meaning. If last month is read purely as past employment, that is a different historical proposition and still omits the required departure. This distinction is for actual human judgment; the proposed errors are not scored totals.'),
('unsupported',['predicate','typed_meaning','source_attribution'],'A clock-only overlap reference cannot establish an owner preference. local date is not a typed calendar date value, and attach_support has no offered equal accepted Claim. It has no newly owned owner support and does not represent the coffee change.'),
('unsupported',['predicate','typed_meaning','source_attribution'],'Retained, but represents a decision to stop coffee rather than the asserted completed habit change. Its exact calendar date is taken from the clock without citing that required clock support; only the owner\'s relative reference is cited. Whether this action/date wording merits partial raw useful credit despite those defects is explicitly left for human review; no required recall match is proposed.'),
('required_useful',[],'Proposed equivalence treats café as the approved café ☕ preference target with a decorative emoji. Denied polarity, whole exact Unicode source, owner and fact encoding are preserved. This is the same unresolved equivalence question as compact-v2 V15, not a new automatic match. Actual human approval is still required.'),
]
assert len(labels)==len(score['unadjudicated'])==13
packet=['# Category-schema compact Qwen output review packet','','Status: **proposed, not human reviewed; no judgments applied**.','','This packet records the 13 unadjudicated raw objects from compact-v3. N01-a is the one automatic exact approved-gold match and is omitted from this judgment list. The run contains 14 raw proposals and 9 retained; 8 retained meanings are still pending. C05 exactly repeats pending compact-v2 V07, so this list is not 13 wholly novel interpretations. All five earlier packets remain unchanged and pending.','','Reference-category and dangling-coordinate failures are gone. Structural retention does not establish meaning. Four objects lack newly owned support and one has incompatible identity. Raw semantic credit cannot repair those rejections or create retained output. “Unsupported” also covers true older facts ineligible as new candidates because they use only overlap.','','[Exact run and request/schema/source seals](reports/development.json) · [Initial score](reports/development-initial-score.json). Source strings below are exact JSON strings; no source/gold labels changed.','','Gold SHA-256: `'+score['gold_sha256']+'`. Initial score SHA-256: `'+sha(reports/'development-initial-score.json')+'`.','','| ID | Case | Exact tuple, summarized | Retained | Proposed label |','| --- | --- | --- | --- | --- |']
decisions=[];indexed=[]
for i,(u,(label,errors,note)) in enumerate(zip(score['unadjudicated'],labels),1):
 run=bycase[u['case_id']];p=next(p for p in run['proposals'] if 'sha256:'+hashlib.sha256(canon(p['wire_raw']).encode()).hexdigest()==u['candidate_sha256']);raw=u['raw_proposal'];id=f'C{i:02d}'
 d={'id':id,'case_id':u['case_id'],'candidate_sha256':u['candidate_sha256'],'label':label,'errors':errors,'note':note,'gold_matches':[0] if i==13 else []};decisions.append(d);indexed.append((d,u,p))
 summary=f"{raw['subject_type']} {raw['predicate']}={raw['object']} ({raw['polarity']}, {raw['kind']})".replace('|','\\|')
 packet.append(f"| {id} | {u['case_id']} | {summary} | {'Yes' if p['retained'] else 'No'} | {label} |")
packet+=['','The judgment choices include C08 optional PostgreSQL raw credit, C10 departure versus historical employment wording, C12 decision/action/date wording versus completed change and missing clock support, and C13 café equivalence. C05 repeats V07 exactly. Existing pending questions are identified for reuse by the review coordinator; no prior packet is reapproved or its labels applied here.']
last=None
for d,u,p in indexed:
 if u['case_id']!=last:
  last=u['case_id'];run=bycase[last];g=gold[last];packet+=['',f'## {last}: exact offered evidence','']
  for field in run['compact']['seal']['sources']:
   s=field['source'];packet += [f"- `{field['alias']}`: {s['ownership']}, {s['authority']}, original bytes {s['start']}:{s['end']}; `{s['event_id']}`; observed {field['observed_at']}; `{s['sha256']}`.",'','```json',json.dumps(s['text'],ensure_ascii=False),'```','']
  if g['expected']:packet+=['Approved case expectations: '+ '; '.join(f"{e['label']}: {e['meaning']['subject']} {e['meaning']['predicate']}={e['meaning']['object']} ({e['meaning']['polarity']}, {e['meaning']['kind']}; temporal {e['meaning']['temporal']!r})" for e in g['expected'])+'.']
  else:packet+=['Approved expectation: no new memory. '+(g.get('forbidden') or g.get('uncertainty') or g.get('no_memory_label',''))]
 packet+=['',f"### {d['id']} — proposed {d['label']}",'',d['note'],'',f"Retained: **{'yes' if p['retained'] else 'no'}**. First structural rejection: `{p.get('rejection') or 'none'}`. Proposed errors: {', '.join(d['errors']) or 'none; equivalence pending'}. Required gold match proposed: {d['gold_matches']}.",'',f"Raw object SHA-256: `{d['candidate_sha256']}`. Occurrences: {u['occurrences']}.",'','```json',canon(u['raw_proposal']),'```']
(new/'output-adjudication-packet.md').write_text('\n'.join(packet)+'\n')
save(new/'output-adjudications.proposed.json',{'schema_version':1,'status':'proposed_not_human_reviewed','reviewer':None,'reviewed_at':None,'packet_file':'output-adjudication-packet.md','packet_sha256':sha(new/'output-adjudication-packet.md'),'source_score_file':'reports/development-initial-score.json','source_score_sha256':sha(reports/'development-initial-score.json'),'gold_sha256':score['gold_sha256'],'decisions':decisions})
prior=json.loads((base/'qwen-compact-v2/reports/paired-comparison.json').read_text());lat=sorted(x['latency_ms'] for x in r['runs']);prior['panels'].append({'configuration':'compact-v3 seed17','original_report':str(reports/'development.json'),'original_report_sha256':sha(reports/'development.json'),'selected_original_run_indexes':list(range(10)),'seeds':[17],'attempted_runs':10,'planned_runs':10,'raw_proposals':14,'retained_proposals':9,'exact_required_matches_raw_and_retained':1,'required_opportunities':6,'latency_p50_ms':lat[4],'latency_p95_ms':lat[8],'latency_max_ms':lat[9],'case_ids':[x['case_id'] for x in r['runs']]});prior['quality_comparison_attempts_across_all_configurations']=110;save(reports/'paired-comparison.json',prior)
resources=json.loads((reports/'development-resources.json').read_text());samples=[resources['baseline'],*resources['samples'],resources['final']]
category_ok=True;coordinate_ok=True
for run in r['runs']:
 aliases={x['alias']:x['source']['ownership'] for x in run['compact']['seal']['sources']}
 for p in run['proposals']:
  for axis in ['sources','context']:
   for ref in p['wire_raw'][axis]:
    category_ok &= ref['ref'] in aliases and ((aliases[ref['ref']]=='context')==(axis=='context'))
    coordinate_ok &= ref.get('selector','whole') in ['whole','date'] and 'start' not in ref and 'end' not in ref or ref.get('selector')=='range' and 'start' in ref and 'end' in ref
save(reports/'measurement-summary.json',{'schema_version':1,'report_sha256':sha(reports/'development.json'),'score_sha256':sha(reports/'development-initial-score.json'),'resources_sha256':sha(reports/'development-resources.json'),'owned_shutdown_sha256':sha(reports/'owned-shutdown.json'),'requests':{'planned':10,'attempted':10,'remaining':0,'all_finished_response':all(x['server_release']=='finished_response' for x in r['runs']),'statuses':score['reports'][0]['statuses']},'raw_proposals':14,'retained_proposals':9,'all_aliases_known_and_in_correct_category':bool(category_ok),'no_dangling_coordinates':bool(coordinate_ok),'resource_samples':len(resources['samples']),'server_rss_kib_baseline':resources['baseline']['server_rss_kib_sum'],'server_rss_kib_peak':max(x['server_rss_kib_sum'] for x in samples),'server_rss_kib_final':resources['final']['server_rss_kib_sum'],'client_rss_kib_peak':max(x['runner_rss_kib_sum'] for x in samples),'host_swap_unique':sorted(set(x['host_swap'] for x in samples)),'elapsed_measurement_seconds':resources['elapsed_seconds'],'prompt_tokens_min':min(x['prompt_tokens'] for x in r['runs']),'prompt_tokens_max':max(x['prompt_tokens'] for x in r['runs']),'output_tokens_min':min(x['output_tokens'] for x in r['runs']),'output_tokens_max':max(x['output_tokens'] for x in r['runs']),'first_request_load_ns':r['runs'][0]['load_ns'],'limitations':resources['limitations']})
print('Saved13-object pending packet, proposed record, paired comparison and resource summary; no labels applied')
