from pathlib import Path
import datetime,hashlib,json,re,shutil
base=Path('cmd/evie/docs/fixtures/memory-stage-4-spike/v1');new=base/'qwen-compact-v2';reports=new/'reports'
def sha(p):return 'sha256:'+hashlib.sha256(p.read_bytes()).hexdigest()
def canon(v):return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False)
def save(p,v):
 with p.open('x') as f:json.dump(v,f,indent=2,ensure_ascii=False);f.write('\n')
r=json.loads((reports/'development.json').read_text());score=json.loads((reports/'development-initial-score.json').read_text());bycase={x['case_id']:x for x in r['runs']};gold={x['case_id']:x for x in json.loads((base/'development.gold.json').read_text())['cases']}
labels=[
('unsupported',['identity','typed_meaning'],'A single pear at lunch does not support an enduring pear habit. The owner/text tuple is also incorrectly marked unresolved.'),
('unsupported',['identity','source_attribution'],'Repeats the older tea preference from overlap alone, with no newly owned support. The explicit owner/text tuple is incorrectly unresolved. Unsupported here means an ineligible repeated truth, not a fabricated historical preference.'),
('unsupported',['identity','source_attribution'],'Treats fiction and an unendorsed Maya report as the owner living in Paris. The owner field is also wrongly duplicated into assistant context.'),
('unwanted_but_true',['typed_meaning','source_attribution'],'Proposed raw judgment treats the writing request as a transient intent, which is not useful enduring memory. It is not an adopted lasting decision; the owner field is wrongly duplicated into assistant context. This request-as-owner-intention interpretation is explicitly for human review and may instead be judged unsupported.'),
('unsupported',['typed_meaning','source_attribution'],'Mentioning Maya\'s report does not assert an enduring owner consideration of that information. It also places owner evidence in assistant context.'),
('unsupported',['identity','source_attribution'],'The new endorsement concerns Maya the neighbor, not the owner. The exact output changes the subject to owner and duplicates owner evidence into assistant context.'),
('unsupported',['typed_meaning'],'The retained tuple says preference=tea and kind=decision. The reviewed statement is a standing tea-over-coffee comparison, not an adopted decision. The assistant question context is now cited correctly, but structural retention does not restore the lost comparison or kind.'),
('unsupported',['typed_meaning','source_attribution'],'The overlap says Maya Chen is a cousin. The proposed owner relationship object omits cousin and has no newly owned support; owner overlap is also duplicated into assistant context.'),
('unsupported',['identity','typed_meaning','temporal','source_attribution'],'The exact tuple gives owner residence=Maya Chen, although Maya Chen is not a place and She is unresolved between two Mayas. It invents present temporal wording and duplicates owner evidence into assistant context.'),
('unsupported',['typed_meaning','source_attribution'],'The overlap says Maya Patel is a colleague. The proposed owner relationship object omits colleague and has no newly owned support; owner overlap is also duplicated into assistant context.'),
('optional_useful',['predicate','source_attribution'],'The raw kind=consideration and future PostgreSQL wording preserve the explicitly unadopted long-term option. Proposed optional raw credit requires human judgment because predicate=decision conflicts with that representation. The owner field is wrongly placed in assistant context; approval would not create retention or required recall.'),
('unsupported',['predicate','typed_meaning','source_attribution'],'Repeats an overlap-only adopted SQLite decision as a preference/fact. There is no new support for that separate proposition, and the owner overlap is wrongly placed in assistant context.'),
('unsupported',['identity','polarity','typed_meaning','source_attribution'],'Affirms employment at Acme after the explicit departure. Acme is emitted as an unoffered accepted entity alias, kind=fact loses world_change, and owner evidence is duplicated into assistant context. Keeping last month does not repair the opposed meaning.'),
('unsupported',['predicate','typed_meaning','source_attribution'],'The tuple is a generic constraint whose date object is the unzoned full clock display. It loses stopped drinking coffee and the denied habit meaning, and wrongly treats the tool observation as assistant context. This is not the explicit coffee-change wording emitted by compact-v1.'),
('required_useful',[],'Proposed equivalence treats café as the same preference target as the approved café ☕ wording, with the emoji decorative. The denied polarity, whole exact Unicode source, owner and fact encoding are preserved. This retained proposal requires actual human equivalence judgment; it is not an automatic exact match.'),
]
assert len(labels)==len(score['unadjudicated'])==15
packet=['# Closed-schema compact Qwen output review packet','','Status: **proposed, not human reviewed; no judgments applied**.','','These are the 15 novel raw objects from the ten-request compact-v2 run. N01-a already matches the approved tea gold exactly and is omitted from this new judgment list. The run has 16 raw proposals and 3 retained; N03-b and N09-a are the two retained objects still requiring meaning review. All four earlier output packets remain unchanged and pending.','','The corrected schema eliminated dangling coordinates. Thirteen objects still fail source-category or identity checks. Raw usefulness judgments cannot repair their structure or turn them into retained candidates. “Unsupported” also covers old facts supported only by overlap; it does not label those historical facts fabricated.','','[Exact run and sealed requests](reports/development.json) · [Initial score](reports/development-initial-score.json). Exact source strings below are JSON strings. The source/gold approval already exists; this packet asks only for new output judgments.','','Gold SHA-256: `'+score['gold_sha256']+'`. Initial score SHA-256: `'+sha(reports/'development-initial-score.json')+'`.','','| ID | Case | Exact tuple, summarized | Retained | Proposed label |','| --- | --- | --- | --- | --- |']
decisions=[];indexed=[]
for i,(u,(label,errors,note)) in enumerate(zip(score['unadjudicated'],labels),1):
 identity=u['candidate_sha256'];run=bycase[u['case_id']];p=next(p for p in run['proposals'] if 'sha256:'+hashlib.sha256(canon(p['wire_raw']).encode()).hexdigest()==identity);raw=u['raw_proposal'];id=f'V{i:02d}'
 d={'id':id,'case_id':u['case_id'],'candidate_sha256':identity,'label':label,'errors':errors,'note':note,'gold_matches':[0] if i==15 else []};decisions.append(d);indexed.append((d,u,p))
 summary=f"{raw['subject_type']} {raw['predicate']}={raw['object']} ({raw['polarity']}, {raw['kind']})".replace('|','\\|')
 packet.append(f"| {id} | {u['case_id']} | {summary} | {'Yes' if p['retained'] else 'No'} | {label} |")
packet+=['','The main judgment choices are V04 (transient writing intent versus unsupported attribution), V07 (whether the shortened tea/decision tuple preserves the asserted meaning), V11 (optional raw PostgreSQL credit despite the predicate error), and V15 (café equivalence). Proposed labels and errors elsewhere are also editable. No label is inferred from source approval.']
last=None
for d,u,p in indexed:
 if u['case_id']!=last:
  last=u['case_id'];run=bycase[last];g=gold[last]
  packet+=['',f'## {last}: exact offered evidence','']
  for field in run['compact']['seal']['sources']:
   s=field['source'];packet += [f"- `{field['alias']}`: {s['ownership']}, {s['authority']}, original bytes {s['start']}:{s['end']}; `{s['event_id']}`; observed {field['observed_at']}; `{s['sha256']}`.",'', '```json',json.dumps(s['text'],ensure_ascii=False),'```','']
  if g['expected']:
   packet+=['Approved case expectations: '+ '; '.join(f"{e['label']}: {e['meaning']['subject']} {e['meaning']['predicate']}={e['meaning']['object']} ({e['meaning']['polarity']}, {e['meaning']['kind']}; temporal {e['meaning']['temporal']!r})" for e in g['expected'])+'.']
  else:packet+=['Approved expectation: no new memory. '+(g.get('forbidden') or g.get('uncertainty') or g.get('no_memory_label',''))]
 packet+=['',f"### {d['id']} — proposed {d['label']}",'',d['note'],'',f"Retained: **{'yes' if p['retained'] else 'no'}**. First structural rejection: `{p.get('rejection') or 'none'}`. Proposed errors: {', '.join(d['errors']) or 'none; equivalence pending'}. Required gold match proposed: {d['gold_matches']}.",'',f"Raw object SHA-256: `{d['candidate_sha256']}`. Occurrences: {u['occurrences']}.",'','```json',canon(u['raw_proposal']),'```']
(new/'output-adjudication-packet.md').write_text('\n'.join(packet)+'\n')
save(new/'output-adjudications.proposed.json',{'schema_version':1,'status':'proposed_not_human_reviewed','reviewer':None,'reviewed_at':None,'packet_file':'output-adjudication-packet.md','packet_sha256':sha(new/'output-adjudication-packet.md'),'source_score_file':'reports/development-initial-score.json','source_score_sha256':sha(reports/'development-initial-score.json'),'gold_sha256':score['gold_sha256'],'decisions':decisions})
# Comparison derives only subsets of existing requests; no new or replayed inference.
panels=[]
for label,path,seeds,known_matches in [('canonical all seeds',base/'qwen/reports/development.json',[17,18],4),('canonical seed17',base/'qwen/reports/development.json',[17],2),('compact-v1 seed17',base/'qwen-compact-v1/reports/development.json',[17],0),('compact-v2 seed17',reports/'development.json',[17],1)]:
 report=json.loads(path.read_text());runs=[x for x in report['runs'] if x['seed'] in seeds];lat=sorted(x['latency_ms'] for x in runs)
 panels.append({'configuration':label,'original_report':str(path),'original_report_sha256':sha(path),'selected_original_run_indexes':[i for i,x in enumerate(report['runs']) if x['seed'] in seeds],'seeds':seeds,'attempted_runs':len(runs),'planned_runs':len(report['planned_cases'])*len(seeds),'raw_proposals':sum(x['raw_count'] for x in runs),'retained_proposals':sum(x['retained_count'] for x in runs),'exact_required_matches_raw_and_retained':known_matches,'required_opportunities':6*len(seeds),'latency_p50_ms':lat[(len(lat)-1)*50//100],'latency_p95_ms':lat[(len(lat)-1)*95//100],'latency_max_ms':lat[-1],'case_ids':[x['case_id'] for x in runs]})
save(reports/'paired-comparison.json',{'schema_version':1,'method':'Descriptive matched case/seed subset; zero inference. Exact automatic matches remain approved-gold matches without pending output judgments. Canonical full repeated totals are context only. p50/p95 use lower-order statistic index floor((n-1)*percent/100).','panels':panels,'quality_comparison_attempts_across_all_configurations':100,'limitations':['One compact pass does not establish within-configuration reproducibility.','No resampling/independence or model-family/production adequacy claim.','Raw meanings and usefulness beyond exact gold remain pending actual human review.']})
resources=json.loads((reports/'development-resources.json').read_text());samples=[resources['baseline'],*resources['samples'],resources['final']]
save(reports/'measurement-summary.json',{'schema_version':1,'report_sha256':sha(reports/'development.json'),'score_sha256':sha(reports/'development-initial-score.json'),'resources_sha256':sha(reports/'development-resources.json'),'owned_shutdown_sha256':sha(reports/'owned-shutdown.json'),'requests':{'planned':10,'attempted':len(r['runs']),'remaining':10-len(r['runs']),'all_finished_response':all(x['server_release']=='finished_response' for x in r['runs']),'statuses':score['reports'][0]['statuses']},'raw_proposals':sum(x['raw_count'] for x in r['runs']),'retained_proposals':sum(x['retained_count'] for x in r['runs']),'no_dangling_coordinates':all(all(ref.get('selector','whole') in ['whole','date'] and 'start' not in ref and 'end' not in ref or ref.get('selector')=='range' and 'start' in ref and 'end' in ref for axis in ['sources','context'] for ref in p['wire_raw'][axis]) for run in r['runs'] for p in run['proposals']),'resource_samples':len(resources['samples']),'server_rss_kib_baseline':resources['baseline']['server_rss_kib_sum'],'server_rss_kib_peak':max(x['server_rss_kib_sum'] for x in samples),'server_rss_kib_final':resources['final']['server_rss_kib_sum'],'client_rss_kib_peak':max(x['runner_rss_kib_sum'] for x in samples),'host_swap_unique':sorted(set(x['host_swap'] for x in samples)),'elapsed_measurement_seconds':resources['elapsed_seconds'],'prompt_tokens_min':min(x['prompt_tokens'] for x in r['runs']),'prompt_tokens_max':max(x['prompt_tokens'] for x in r['runs']),'output_tokens_min':min(x['output_tokens'] for x in r['runs']),'output_tokens_max':max(x['output_tokens'] for x in r['runs']),'first_request_load_ns':r['runs'][0]['load_ns'],'limitations':resources['limitations']})
print('Saved15-object pending packet, proposed record, paired comparison and measured summary')
