await page.getByRole('button',{name:/Keep answers concise/}).click();
await page.getByRole('region',{name:'Memory detail',exact:true}).waitFor({timeout:5000});
await page.getByRole('button',{name:'David',exact:true}).click();
await page.getByRole('heading',{name:'David',exact:true}).waitFor({timeout:5000});
await page.getByRole('button',{name:/Back to memories/}).click();
await page.getByRole('button',{name:'Graph',exact:true}).click();
await page.getByRole('button',{name:'Open Keep answers concise; avoid data dumps.',exact:true}).click();
await page.getByRole('region',{name:'Memory detail',exact:true}).waitFor({timeout:5000});
await page.getByRole('button',{name:/Back to memories/}).click();
await page.getByRole('button',{name:'Review',exact:true}).click();
await page.getByText('Nothing to review.',{exact:true}).waitFor({timeout:5000});
await page.locator('summary[aria-label="Memory tools"]').click();
await page.getByRole('button',{name:'Background activity',exact:true}).click();
await page.getByRole('heading',{name:'Background activity',exact:true}).waitFor({timeout:5000});
await page.getByRole('button',{name:'Memories',exact:true}).click();
await page.getByRole('button',{name:/Keep answers concise/}).waitFor({timeout:5000});
await page.screenshot({path:'/Users/davidboktor/code/evie/.scratch/memory-ux/live-list.png'});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/Users/davidboktor/code/evie/.scratch/memory-ux/live-mobile-list.png'});
const result={overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),errors};
require('node:fs').writeFileSync('/Users/davidboktor/code/evie/.scratch/memory-ux/browser-final.json',JSON.stringify(result));
return result;
