import { useState } from "react";
import type { CandidateProposal, IdentityChoices, IdentityOptions, OwnerCandidate, TemporalOptions } from "../api/candidateReview";
import type { CandidateInboxController, InboxState, InterpretationHistory } from "./controller";
import { IdentityLineage, CorrectionLineage, CandidateSources, EditLineage, ProposalMeaning } from "./ReviewDisclosure";

const button = "border-hair-input text-body hover:bg-hover rounded border px-3 py-2 text-xs disabled:opacity-40";
const input = "border-hair-input bg-app w-full rounded border px-3 py-2 text-xs";

export function AdvancedReviewForms({ state, controller }: { state: InboxState; controller?: CandidateInboxController }) {
 const item = state.detail; const [editing, setEditing] = useState(false);
 if (!item || item.redacted) return null;
 return <section aria-label="Interpretation review" className="mt-4 space-y-3">
  {item.original && <details><summary>Original extraction retained</summary><ProposalMeaning proposal={item.original.proposal}/><CandidateSources title="Original supporting evidence" sources={item.original.support ?? []}/><CandidateSources title="Original context" sources={item.original.context ?? []}/></details>}
  {item.identity && <IdentityLineage identity={item.identity}/>}
  {item.temporal && <CorrectionLineage correction={item.temporal}/>}
  {item.candidate.review_state === "unresolved" && <>
   {item.candidate.proposal.identity && <><p className="text-amber-ink">Additional identity review: explicitly choose an existing identity or create a distinct definition.</p><button className={button} disabled={state.busy || !controller} onClick={() => void controller?.loadIdentityOptions()}>Inspect identity alternatives</button></>}
   {state.identityOptions && <IdentityForm key={state.identityOptions.options_sha256} item={item} options={state.identityOptions} disabled={state.busy || !controller} onChoose={(choices) => void controller?.chooseIdentity({ candidate: state.identityOptions!.candidate, options_sha256: state.identityOptions!.options_sha256, choices })}/>}
   {item.candidate.proposal.temporal?.correction && <><p>Choose the exact earlier claim and whether it was wrong or the world changed. Unknown effective times remain unknown.</p><button className={button} disabled={state.busy || !controller} onClick={() => void controller?.loadTemporalOptions()}>Inspect correction alternatives</button></>}
   {state.temporalOptions && <TemporalForm key={state.temporalOptions.options_sha256} options={state.temporalOptions} disabled={state.busy || !controller} onChoose={(choice) => void controller?.chooseTemporal({ candidate: state.temporalOptions!.candidate, options_sha256: state.temporalOptions!.options_sha256, choice })}/>}
   <button className={`${button} block`} disabled={state.busy || !controller} onClick={() => setEditing(!editing)}>{editing ? "Close edit draft" : "Edit interpretation"}</button>
   {editing && <EditForm item={item} disabled={state.busy || !controller} onEdit={(proposal, reason, candidate) => void controller?.edit({ candidate, proposal, reason })}/>}
  </>}
  {item.ref.interpretation_revision > 0 && <HistoryForm maximum={item.ref.interpretation_revision} state={state} controller={controller}/>}
 </section>;
}

function HistoryForm({ maximum, state, controller }: { maximum: number; state: InboxState; controller?: CandidateInboxController }) {
 const [kind, setKind] = useState<InterpretationHistory["kind"]>("edit"); const [revision, setRevision] = useState(1);
 const history = state.history?.kind === kind && state.history.value.revision === revision ? state.history : undefined;
 const valid = Number.isSafeInteger(revision) && revision >= 1 && revision <= maximum;
 return <details><summary>Inspect interpretation history</summary><p className="mt-2 text-xs">Edits, identity choices and correction choices share one revision sequence. Select the recorded kind and revision; a number may belong to a different kind.</p><form className="mt-2 space-y-2" onSubmit={(event) => { event.preventDefault(); if (valid) void controller?.loadHistoryRevision(kind, revision); }}><fieldset disabled={state.busy || !controller} className="space-y-2"><label className="block text-xs">History kind<select aria-label="Interpretation history kind" className={input} value={kind} onChange={(event) => { const value = event.target.value; if (value === "edit" || value === "identity" || value === "correction") setKind(value); }}><option value="edit">Owner edit</option><option value="identity">Identity choice</option><option value="correction">Correction choice</option></select></label><label className="block text-xs">Interpretation revision<input aria-label="Interpretation history revision" className={input} type="number" min={1} max={maximum} step={1} value={revision} onChange={(event) => setRevision(Number(event.target.value))}/></label><button className={button} disabled={!valid} type="submit">Load immutable history revision</button></fieldset></form>{history?.kind === "edit" && <EditLineage edit={history.value}/>} {history?.kind === "identity" && <IdentityLineage identity={history.value}/>} {history?.kind === "correction" && <CorrectionLineage correction={history.value}/>}</details>;
}

function IdentityForm({ item, options, disabled, onChoose }: { item: OwnerCandidate; options: IdentityOptions; disabled: boolean; onChoose: (choices: IdentityChoices) => void }) {
 const [selected, setSelected] = useState({ subject: "", object: "", predicate: "" }); const proposal = item.candidate.proposal.identity!;
 const choose = (field: keyof typeof selected, value: string) => setSelected({ ...selected, [field]: value });
 const complete = (!proposal.subject || selected.subject) && (!proposal.object || selected.object) && (!proposal.predicate || selected.predicate);
 return <form aria-label="Identity choices" className="border-hair space-y-4 rounded border p-3" onSubmit={(event) => { event.preventDefault(); if (!complete) return; onChoose({ subject: proposal.subject ? { entity_id: selected.subject === "create" ? "" : selected.subject, create: selected.subject === "create" } : null, object: proposal.object ? { entity_id: selected.object === "create" ? "" : selected.object, create: selected.object === "create" } : null, predicate: proposal.predicate ? { predicate_id: selected.predicate === "create" ? "" : selected.predicate, create: selected.predicate === "create" } : null }); }}>
  {(["subject", "object"] as const).map((field) => proposal[field] && <fieldset key={field} disabled={disabled}><legend className="font-medium">{field === "subject" ? "Subject" : "Object"}: {proposal[field]!.name} ({proposal[field]!.entity_type})</legend>{options[field].map((alternative) => <label className="mt-3 block text-xs" key={alternative.entity.entity_id}><input type="radio" name={`identity-${field}`} value={alternative.entity.entity_id} checked={selected[field] === alternative.entity.entity_id} onChange={(event) => choose(field, event.target.value)}/> Reuse {alternative.entity.canonical_name} · {alternative.entity.entity_type} · {alternative.entity.scope_key} · {alternative.entity.entity_id}<span className="text-muted-text mt-1 block">Aliases: {alternative.aliases.map((alias) => alias.value).join(", ") || "None"}</span>{alternative.context.map((claim) => <span className="mt-1 block" key={claim.claim_id}>Known context: {claim.predicate.label} · {claim.polarity} · {claim.object.literal?.value ?? claim.object.entity_id} · claim {claim.claim_id} · {claim.valid_time.from ?? "Unknown"} / {claim.valid_time.to ?? "Unknown"}</span>)}</label>)}<label className="mt-3 block text-xs"><input type="radio" name={`identity-${field}`} value="create" checked={selected[field] === "create"} onChange={() => choose(field, "create")}/> Create distinct Entity “{proposal[field]!.name}” in {item.destination}</label></fieldset>)}
  {proposal.predicate && <fieldset disabled={disabled}><legend className="font-medium">Relationship definition (global)</legend><p className="text-xs">Proposed: {proposal.predicate.label} · token {proposal.predicate.token} · object {proposal.predicate.object_constraint} · cardinality {proposal.predicate.cardinality}</p>{options.predicates.map((predicate) => <label className="mt-2 block text-xs" key={predicate.predicate_id}><input type="radio" name="identity-predicate" checked={selected.predicate === predicate.predicate_id} onChange={() => choose("predicate", predicate.predicate_id)}/> Reuse {predicate.label} · {predicate.token} v{predicate.version} · {predicate.object_constraint} · {predicate.cardinality} · {predicate.predicate_id}</label>)}<label className="mt-2 block text-xs"><input type="radio" name="identity-predicate" checked={selected.predicate === "create"} onChange={() => choose("predicate", "create")}/> Create the displayed new global Predicate definition</label></fieldset>}
  <p className="text-muted-text text-xs">This records interpretation only. Preview the generated identities, Aliases and claims before accepting.</p><button className={button} disabled={disabled || !complete} type="submit">Record these identity choices</button>
 </form>;
}

function TemporalForm({ options, disabled, onChoose }: { options: TemporalOptions; disabled: boolean; onChoose: (choice: { old_claim_id: string; mode: string }) => void }) {
 const [claim, setClaim] = useState(""); const [mode, setMode] = useState("");
 return <form aria-label="Correction choices" className="border-hair space-y-3 rounded border p-3" onSubmit={(event) => { event.preventDefault(); if (claim && mode) onChoose({ old_claim_id: claim, mode }); }}><fieldset disabled={disabled}><legend>Exact earlier claim</legend>{options.alternatives.map((alt) => <label className="mt-2 block text-xs" key={alt.claim.claim_id}><input type="radio" name="old-claim" checked={claim === alt.claim.claim_id} onChange={() => setClaim(alt.claim.claim_id)}/> {alt.claim.predicate.label}: {alt.claim.polarity} {alt.claim.object.literal?.value ?? alt.claim.object.entity_id} · {alt.state.state} · {alt.claim.claim_id} · valid {alt.claim.valid_time.from ?? "Unknown"} / {alt.claim.valid_time.to ?? "Unknown"}</label>)}</fieldset><fieldset disabled={disabled}><legend>Correction meaning</legend>{options.modes.map((value) => <label className="mt-2 block text-xs" key={value}><input type="radio" name="correction-mode" checked={mode === value} onChange={() => setMode(value)}/> {value === "error" ? "Error: earlier statement was wrong" : value === "changed" ? "Changed: the real-world state changed" : value}</label>)}</fieldset><p>Source-proposed effective time: {options.effective_time ?? "Unknown; a changed correction may require an edited, sourced interpretation or a separate assertion."}</p><button className={button} type="submit" disabled={disabled || !claim || !mode}>Record this correction choice</button></form>;
}

function EditForm({ item, disabled, onEdit }: { item: OwnerCandidate; disabled: boolean; onEdit: (proposal: CandidateProposal, reason: string, ref: OwnerCandidate["ref"]) => void }) {
 // Keep the draft bound to its starting revision across an asynchronous refresh.
 // The owner can inspect a newer revision, but must explicitly restart this edit.
 const [start] = useState(item); const [proposal, setProposal] = useState<CandidateProposal>(() => structuredClone({ ...item.candidate.proposal, support: item.candidate.proposal.support ?? item.candidate.support?.map((source) => source.locator) ?? [], context: item.candidate.proposal.context ?? item.candidate.context?.map((source) => source.locator) ?? [] })); const [reason, setReason] = useState("");
 const stale = start.ref.interpretation_revision !== item.ref.interpretation_revision || start.ref.review_revision !== item.ref.review_revision;
 const setProp = (patch: Partial<CandidateProposal>) => setProposal({ ...proposal, ...patch });
 const objectKind = proposal.proposition.object.literal?.kind ?? "entity";
 return <form aria-label="Edit candidate interpretation" className="border-hair space-y-3 rounded border p-3" onSubmit={(event) => { event.preventDefault(); onEdit(proposal, reason, start.ref); }}><p>Editing interpretation {start.ref.interpretation_revision}, review {start.ref.review_revision}. Original extraction and evidence remain retained.</p>{stale && <p role="alert">The candidate has a newer revision. This draft remains bound to its original revision. Close and reopen the edit to start from the refreshed interpretation.</p>}<div className="grid gap-3 md:grid-cols-2"><section><h4>Before</h4><ProposalMeaning proposal={start.candidate.proposal}/></section><section><h4>Draft after edit</h4><ProposalMeaning proposal={proposal}/></section></div>
  <fieldset disabled={disabled || stale} className="space-y-3">
   <label className="block text-xs">Subject Entity ID<input aria-label="Edited subject Entity ID" className={input} value={proposal.proposition.subject_entity_id} onChange={(event) => setProp({ proposition: { ...proposal.proposition, subject_entity_id: event.target.value } })}/></label>
   <label className="block text-xs">Predicate ID<input aria-label="Edited Predicate ID" className={input} value={proposal.proposition.predicate_id} onChange={(event) => setProp({ proposition: { ...proposal.proposition, predicate_id: event.target.value } })}/></label>
   <label className="block text-xs">Object kind<select className={input} value={objectKind} onChange={(event) => setProp({ proposition: { ...proposal.proposition, object: event.target.value === "entity" ? { entity_id: "" } : { literal: { kind: event.target.value, value: "" } } } })}>{["entity", "text", "integer", "decimal", "boolean", "date", "datetime"].map((kind) => <option key={kind}>{kind}</option>)}</select></label>
   <label className="block text-xs">{objectKind === "entity" ? "Object Entity ID" : "Literal value"}<input aria-label="Edited object value" className={input} value={proposal.proposition.object.literal?.value ?? proposal.proposition.object.entity_id ?? ""} onChange={(event) => setProp({ proposition: { ...proposal.proposition, object: objectKind === "entity" ? { entity_id: event.target.value } : { literal: { kind: objectKind, value: event.target.value } } } })}/></label>
   <label className="block text-xs">Polarity<select aria-label="Edited polarity" className={input} value={proposal.proposition.polarity} onChange={(event) => setProp({ proposition: { ...proposal.proposition, polarity: event.target.value } })}><option value="affirmed">Affirmed</option><option value="denied">Denied</option></select></label>
   {(["from", "to"] as const).map((bound) => <label className="block text-xs" key={bound}>Valid {bound === "from" ? "from" : "until"} (empty means unknown)<input aria-label={`Edited valid ${bound}`} className={input} value={proposal.valid_time[bound] ?? ""} onChange={(event) => setProp({ valid_time: { ...proposal.valid_time, [bound]: event.target.value || null } })}/></label>)}
   <label className="block text-xs">Time qualification<input aria-label="Edited time qualification" className={input} value={proposal.temporal_qualification} onChange={(event) => setProp({ temporal_qualification: event.target.value })}/></label>
   {proposal.temporal && <><label className="block text-xs">Meaning<select aria-label="Edited meaning" className={input} value={proposal.temporal.meaning} onChange={(event) => setProp({ temporal: { ...proposal.temporal!, meaning: event.target.value } })}>{["assertion", "plan", "possibility"].map((meaning) => <option key={meaning}>{meaning}</option>)}</select></label>{proposal.temporal.correction && <><label className="block text-xs">Correction effective time (empty means unknown)<input aria-label="Edited correction effective time" className={input} value={proposal.temporal.correction.effective_time ?? ""} onChange={(event) => setProp({ temporal: { ...proposal.temporal!, correction: { ...proposal.temporal!.correction!, effective_time: event.target.value || null } } })}/></label><button type="button" className={button} onClick={() => setProp({ temporal: { ...proposal.temporal!, correction: null } })}>Interpret as separate assertion without superseding an earlier claim</button></>}</>}
   {proposal.identity && <><h4>Sourced unresolved definitions</h4>{(["subject", "object"] as const).map((field) => proposal.identity?.[field] && <label key={field} className="block text-xs">{field} mention<input className={input} value={proposal.identity[field]!.name} onChange={(event) => setProp({ identity: { ...proposal.identity!, [field]: { ...proposal.identity![field], name: event.target.value } } })}/></label>)}{proposal.identity.predicate && (["token", "label", "object_constraint", "cardinality"] as const).map((field) => <label className="block text-xs" key={field}>Predicate {field}<input className={input} value={proposal.identity!.predicate![field]} onChange={(event) => setProp({ identity: { ...proposal.identity!, predicate: { ...proposal.identity!.predicate!, [field]: event.target.value } } })}/></label>)}</>}
   <p className="text-muted-text text-xs">Supporting and context locators stay bound to the original source window. The Kernel validates the edited meaning and all source eligibility.</p><CandidateSources title="Evidence retained by this edit" sources={start.candidate.support ?? []}/><CandidateSources title="Interpretation context retained by this edit" sources={start.candidate.context ?? []}/>
   <label className="block text-xs">Edit reason<input aria-label="Edit reason" className={input} value={reason} onChange={(event) => setReason(event.target.value)}/></label>
   <button className={button} type="submit">Record edited interpretation</button>
  </fieldset>
 </form>;
}
